# Generated by Django 5.1.7 on 2025-03-16 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_admin_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriere',
            name='sportiv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rezultat',
            name='sportiv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezultate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='competitie',
            old_name='admin',
            new_name='organizator',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sportiv', 'Sportiv'), ('organizator', 'Organizator')], default='sportiv', max_length=20),
        ),
        migrations.DeleteModel(
            name='Sportiv',
        ),
    ]
