# Generated by Django 5.1.7 on 2025-03-16 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inscriere_sportiv_alter_rezultat_sportiv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezultat',
            old_name='sportiv',
            new_name='castigator',
        ),
        migrations.RemoveField(
            model_name='meci',
            name='data',
        ),
        migrations.RemoveField(
            model_name='meci',
            name='runda',
        ),
        migrations.AddField(
            model_name='inscriere',
            name='categorie',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='inscriere',
            name='varsta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meci',
            name='sportivi',
            field=models.ManyToManyField(through='api.Rezultat', to=settings.AUTH_USER_MODEL),
        ),
    ]
