# Generated by Django 5.1.7 on 2025-03-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_sportiv_rezultat_castigator_remove_meci_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriere',
            name='categorie',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
