# Generated by Django 5.1.7 on 2025-04-22 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_inscriere_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('varsta_min', models.IntegerField()),
                ('varsta_max', models.IntegerField()),
                ('greutate_min', models.FloatField()),
                ('greutate_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saltea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meci',
            name='sportivi',
        ),
        migrations.AddField(
            model_name='inscriere',
            name='greutate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meci',
            name='castigator',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meciuri_castigate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meci',
            name='diferenta_activata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meci',
            name='scor1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meci',
            name='scor2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meci',
            name='sportiv1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meciuri_ca_sportiv1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meci',
            name='sportiv2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meciuri_ca_sportiv2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscriere',
            name='competitie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to='api.competitie'),
        ),
        migrations.AlterField(
            model_name='inscriere',
            name='sportiv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meci',
            name='competitie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meciuri', to='api.competitie'),
        ),
        migrations.AddField(
            model_name='meci',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categorie'),
        ),
        migrations.AlterField(
            model_name='inscriere',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to='api.categorie'),
        ),
        migrations.CreateModel(
            name='ClasamentProba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puncte', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categorie')),
                ('competitie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.competitie')),
                ('sportiv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClasamentClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puncte', models.IntegerField(default=0)),
                ('competitie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.competitie')),
                ('club', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.club')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.club'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='proba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorii', to='api.proba'),
        ),
        migrations.AddField(
            model_name='meci',
            name='saltea',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.saltea'),
        ),
        migrations.DeleteModel(
            name='Rezultat',
        ),
    ]
