# Generated by Django 5.1.7 on 2025-04-25 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categorie_club_proba_saltea_remove_meci_sportivi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='clasamentclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.club'),
        ),
        migrations.AlterField(
            model_name='clasamentclub',
            name='competitie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competitie'),
        ),
        migrations.AlterField(
            model_name='clasamentproba',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorie'),
        ),
        migrations.AlterField(
            model_name='clasamentproba',
            name='competitie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competitie'),
        ),
        migrations.AlterField(
            model_name='inscriere',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to='api.categorie'),
        ),
        migrations.AlterField(
            model_name='inscriere',
            name='competitie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to='api.competitie'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorie'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='competitie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meciuri', to='api.competitie'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='saltea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.saltea'),
        ),
        migrations.CreateModel(
            name='Sportiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('cnp', models.CharField(max_length=13, unique=True)),
                ('sex', models.CharField(max_length=10)),
                ('data_nastere', models.DateField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.club')),
            ],
        ),
        migrations.AlterField(
            model_name='clasamentproba',
            name='sportiv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sportiv'),
        ),
        migrations.AlterField(
            model_name='inscriere',
            name='sportiv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscrieri', to='api.sportiv'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='castigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meciuri_castigate', to='api.sportiv'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='sportiv1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meciuri_ca_sportiv1', to='api.sportiv'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='sportiv2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meciuri_ca_sportiv2', to='api.sportiv'),
        ),
    ]
