# Generated by Django 5.1.7 on 2025-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_club_remove_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitie',
            name='organizator',
        ),
        migrations.AddField(
            model_name='competitie',
            name='adresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competitie',
            name='locatie_google_maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitie',
            name='oras',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
