# Generated by Django 5.1.7 on 2025-04-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_competitie_organizator_competitie_adresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitie',
            name='locatie_google_maps',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
