# Generated by Django 5.1.7 on 2025-04-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_competitie_locatie_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitie',
            name='locatie_google_maps',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
