# Generated by Django 5.1.7 on 2025-05-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_competitie_locatie_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitie',
            name='probe',
            field=models.ManyToManyField(related_name='competitii', to='api.proba'),
        ),
    ]
