# Generated by Django 5.1.7 on 2025-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_competitie_probe'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriere',
            name='meci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sportiv',
            name='nr_legitimatie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
