# Generated by Django 5.1.7 on 2025-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_inscriere_meci_sportiv_nr_legitimatie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='greutate_max',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='greutate_min',
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie_greutate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
