# Generated by Django 5.1.7 on 2025-05-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_categorie_greutate_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriere',
            name='greutate',
        ),
    ]
