# Generated by Django 5.1.7 on 2025-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_inscriere_greutate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriere',
            name='meci_demonstrativ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
