# Generated by Django 5.1.7 on 2025-05-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_inscriere_meci_demonstrativ'),
    ]

    operations = [
        migrations.AddField(
            model_name='meci',
            name='next_meci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meciuri_precedente', to='api.meci'),
        ),
        migrations.AddField(
            model_name='meci',
            name='pozitie_in_bracket',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meci',
            name='pozitie_in_runda',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meci',
            name='runda',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meci',
            name='saltea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.saltea'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='sportiv1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meciuri_ca_sportiv1', to='api.sportiv'),
        ),
        migrations.AlterField(
            model_name='meci',
            name='sportiv2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meciuri_ca_sportiv2', to='api.sportiv'),
        ),
    ]
